/// Updated at 03/20/2021 15:20:51
Class sp.NewClass9 Extends %Persistent [ Language = objectscript ]
{

Storage Default
{
<Data name="NewClass9DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^sp.NewClass9D</DataLocation>
<DefaultData>NewClass9DefaultData</DefaultData>
<IdLocation>^sp.NewClass9D</IdLocation>
<IndexLocation>^sp.NewClass9I</IndexLocation>
<StreamLocation>^sp.NewClass9S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

